version: "3.8"
services:
  xgproyect-v3:
    build:
      context: .
      args:
        PHP_VERSION: 7.4
    container_name: xgproyect-v3
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: on-failure
    ports:
      - 33060:3306
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: xgp
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: on-failure
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
