name: PHP Tests

on:
  push:
    branches: '**'
  pull_request:

jobs:
  test:
    name: Run Unit Testing
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: gd, mysqli, opcache, zip

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run phpunit
      run: composer phpunit
  lint:
    name: Run Lint
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: gd, mysqli, opcache, zip

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run phplint
      uses: overtrue/phplint@4.1.0
      with:
        path: app/
        options: --exclude=*.log --exclude=vendor
  php-cs-fixer:
    name: Run PHP CS Fixer
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: docker://oskarstark/php-cs-fixer-ga:3.4.0.1
      with:
        args: --diff --dry-run app/
